data:
  image: busybox:latest
  volumes:
    - .:/app
db:
  image: postgres:9.4
  volumes_from:
    - data
  environment:
    POSTGRES_USER: devuser
  expose:
    - "5432"
web:
  build: .
  command: bundle exec rails s -b 0.0.0.0
  volumes_from:
    - data
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    TZ: Asia/Tokyo
    LANG: C.UTF-8
    RAILS_DATABASE_HOST: db
